package com.example.myapplication.fenquan.service;

import com.example.myapplication.fenquan.dao.FenquanDao;
import com.example.myapplication.fenquan.entity.Copy1;
import com.example.myapplication.fenquan.entity.Workbench;

import java.util.List;

public class WorkbenchService {

    private FenquanDao base;

    public List<Workbench> getList(String company) {
        String sql = "select * from baitaoquanxian where 公司=? order by 日期 desc";
        base = new FenquanDao();
        List<Workbench> list = base.query(Workbench.class, sql, company);
        return list;
    }

    public List<Workbench> queryList(String company,String start_date, String stop_date) {
        String sql = "select * from baitaoquanxian where 公司=? and 日期 >= ?  and 日期 <= ? order by 日期 desc";
        base = new FenquanDao();
        List<Workbench> list = base.query(Workbench.class, sql, company, start_date,stop_date);
        return list;
    }

    public boolean insert(Workbench workbench) {
        String sql = "insert into baitaoquanxian(人员,公司,日期,a最后修改日期) values(?,?,?,?)";
        base = new FenquanDao();
        long result = base.executeOfId(sql, workbench.get人员(), workbench.get公司(), workbench.get日期(), workbench.getA最后修改日期());
        return result > 0;
    }

    public boolean update(Workbench workbench) {
        String sql = "update baitaoquanxian set a最后修改日期=?,A=?,B=?,C=?,D=?,E=?,F=?,G=?,H=?,I=?,J=?,K=?,L=?,M=?,N=?,O=?,P=?,Q=?,R=?,S=?,T=?,U=?,V=?,W=?,X=?,Y=?,Z=?,AA=?,AB=?,AC=?,AD=?,AE=?,AF=?,AG=?,AH=?,AI=?,AJ=?,AK=?,AL=?,AM=?,AN=?,AO=?,AP=?,AQ=?,AR=?,ASS=?,AT=?,AU=?,AV=?,AW=?,AX=?,AY=?,AZ=?,BA=?,BB=?,BC=?,BD=?,BE=?,BF=?,BG=?,BH=?,BI=?,BJ=?,BK=?,BL=?,BM=?,BN=?,BO=?,BP=?,BQ=?,BR=?,BS=?,BT=?,BU=?,BV=?,BW=?,BX=?,BYY=?,BZ=?,CA=?,CB=?,CC=?,CD=?,CE=?,CF=?,CG=?,CH=?,CI=?,CJ=?,CK=?,CL=?,CM=?,CN=?,CO=?,CP=?,CQ=?,CR=?,CS=?,CT=?,CU=?,CV=? where id = ?";
        base = new FenquanDao();
        return base.execute(sql, workbench.getA最后修改日期(), workbench.getA(), workbench.getB(), workbench.getC(), workbench.getD(), workbench.getE(), workbench.getF(), workbench.getG(), workbench.getH(), workbench.getI(), workbench.getJ(), workbench.getK(), workbench.getL(), workbench.getM(), workbench.getN(), workbench.getO(), workbench.getP(), workbench.getQ(), workbench.getR(), workbench.getS(), workbench.getT(), workbench.getU(), workbench.getV(), workbench.getW(), workbench.getX(), workbench.getY(), workbench.getZ(), workbench.getAa(), workbench.getAb(), workbench.getAc(), workbench.getAd(), workbench.getAe(), workbench.getAf(), workbench.getAg(), workbench.getAh(), workbench.getAi(), workbench.getAj(), workbench.getAk(), workbench.getAl(), workbench.getAm(), workbench.getAn(), workbench.getAo(), workbench.getAp(), workbench.getAq(), workbench.getAr(), workbench.getAss(), workbench.getAt(), workbench.getAu(), workbench.getAv(), workbench.getAw(), workbench.getAx(), workbench.getAy(), workbench.getAz(), workbench.getBa(), workbench.getBb(), workbench.getBc(), workbench.getBd(), workbench.getBe(), workbench.getBf(), workbench.getBg(), workbench.getBh(), workbench.getBi(), workbench.getBj(), workbench.getBk(), workbench.getBl(), workbench.getBm(), workbench.getBn(), workbench.getBo(), workbench.getBp(), workbench.getBq(), workbench.getBr(), workbench.getBs(), workbench.getBt(), workbench.getBu(), workbench.getBv(), workbench.getBw(), workbench.getBx(), workbench.getByy(), workbench.getBz(), workbench.getCa(), workbench.getCb(), workbench.getCc(), workbench.getCd(), workbench.getCe(), workbench.getCf(), workbench.getCg(), workbench.getCh(), workbench.getCi(), workbench.getCj(), workbench.getCk(), workbench.getCl(), workbench.getCm(), workbench.getCn(), workbench.getCo(), workbench.getCp(), workbench.getCq(), workbench.getCr(), workbench.getCs(), workbench.getCt(), workbench.getCu(), workbench.getCv(),workbench.getId());
    }

    public boolean delete(int id) {
        String sql = "delete from baitaoquanxian where id = ?";
        base = new FenquanDao();
        return base.execute(sql, id);
    }

    public List<Workbench> getChart(String company,String start_date, String stop_date) {
        String sql = "select sum(case when isnull(A,'') !='' then 1 else 0 end ) as A,sum(case when isnull(B,'') !='' then 1 else 0 end ) as B,sum(case when isnull(C,'') !='' then 1 else 0 end ) as C,sum(case when isnull(D,'') !='' then 1 else 0 end ) as D,sum(case when isnull(E,'') !='' then 1 else 0 end ) as E,sum(case when isnull(F,'') !='' then 1 else 0 end ) as F,sum(case when isnull(G,'') !='' then 1 else 0 end ) as G,sum(case when isnull(H,'') !='' then 1 else 0 end ) as H,sum(case when isnull(I,'') !='' then 1 else 0 end ) as I,sum(case when isnull(J,'') !='' then 1 else 0 end ) as J,sum(case when isnull(K,'') !='' then 1 else 0 end ) as K,sum(case when isnull(L,'') !='' then 1 else 0 end ) as L,sum(case when isnull(M,'') !='' then 1 else 0 end ) as M,sum(case when isnull(N,'') !='' then 1 else 0 end ) as N,sum(case when isnull(O,'') !='' then 1 else 0 end ) as O,sum(case when isnull(P,'') !='' then 1 else 0 end ) as P,sum(case when isnull(Q,'') !='' then 1 else 0 end ) as Q,sum(case when isnull(R,'') !='' then 1 else 0 end ) as R,sum(case when isnull(S,'') !='' then 1 else 0 end ) as S,sum(case when isnull(T,'') !='' then 1 else 0 end ) as T,sum(case when isnull(U,'') !='' then 1 else 0 end ) as U,sum(case when isnull(V,'') !='' then 1 else 0 end ) as V,sum(case when isnull(W,'') !='' then 1 else 0 end ) as W,sum(case when isnull(X,'') !='' then 1 else 0 end ) as X,sum(case when isnull(Y,'') !='' then 1 else 0 end ) as Y,sum(case when isnull(Z,'') !='' then 1 else 0 end ) as Z,sum(case when isnull(AA,'') !='' then 1 else 0 end ) as AA,sum(case when isnull(AB,'') !='' then 1 else 0 end ) as AB,sum(case when isnull(AC,'') !='' then 1 else 0 end ) as AC,sum(case when isnull(AD,'') !='' then 1 else 0 end ) as AD,sum(case when isnull(AE,'') !='' then 1 else 0 end ) as AE,sum(case when isnull(AF,'') !='' then 1 else 0 end ) as AF,sum(case when isnull(AG,'') !='' then 1 else 0 end ) as AG,sum(case when isnull(AH,'') !='' then 1 else 0 end ) as AH,sum(case when isnull(AI,'') !='' then 1 else 0 end ) as AI,sum(case when isnull(AJ,'') !='' then 1 else 0 end ) as AJ,sum(case when isnull(AK,'') !='' then 1 else 0 end ) as AK,sum(case when isnull(AL,'') !='' then 1 else 0 end ) as AL" +
                ",sum(case when isnull(AM,'') !='' then 1 else 0 end ) as AM,sum(case when isnull(AN,'') !='' then 1 else 0 end ) as AN,sum(case when isnull(AO,'') !='' then 1 else 0 end ) as AO,sum(case when isnull(AP,'') !='' then 1 else 0 end ) as AP,sum(case when isnull(AQ,'') !='' then 1 else 0 end ) as AQ,sum(case when isnull(AR,'') !='' then 1 else 0 end ) as AR,sum(case when isnull(ASS,'') !='' then 1 else 0 end ) as ASS,sum(case when isnull(AT,'') !='' then 1 else 0 end ) as AT,sum(case when isnull(AU,'') !='' then 1 else 0 end ) as AU,sum(case when isnull(AV,'') !='' then 1 else 0 end ) as AV,sum(case when isnull(AW,'') !='' then 1 else 0 end ) as AW,sum(case when isnull(AX,'') !='' then 1 else 0 end ) as AX,sum(case when isnull(AY,'') !='' then 1 else 0 end ) as AY,sum(case when isnull(AZ,'') !='' then 1 else 0 end ) as AZ,sum(case when isnull(BA,'') !='' then 1 else 0 end ) as BA,sum(case when isnull(BB,'') !='' then 1 else 0 end ) as BB,sum(case when isnull(BC,'') !='' then 1 else 0 end ) as BC,sum(case when isnull(BD,'') !='' then 1 else 0 end ) as BD,sum(case when isnull(BE,'') !='' then 1 else 0 end ) as BE,sum(case when isnull(BF,'') !='' then 1 else 0 end ) as BF,sum(case when isnull(BG,'') !='' then 1 else 0 end ) as BG,sum(case when isnull(BH,'') !='' then 1 else 0 end ) as BH,sum(case when isnull(BI,'') !='' then 1 else 0 end ) as BI,sum(case when isnull(BJ,'') !='' then 1 else 0 end ) as BJ,sum(case when isnull(BK,'') !='' then 1 else 0 end ) as BK,sum(case when isnull(BL,'') !='' then 1 else 0 end ) as BL,sum(case when isnull(BM,'') !='' then 1 else 0 end ) as BM,sum(case when isnull(BN,'') !='' then 1 else 0 end ) as BN,sum(case when isnull(BO,'') !='' then 1 else 0 end ) as BO,sum(case when isnull(BP,'') !='' then 1 else 0 end ) as BP,sum(case when isnull(BQ,'') !='' then 1 else 0 end ) as BQ,sum(case when isnull(BR,'') !='' then 1 else 0 end ) as BR,sum(case when isnull(BS,'') !='' then 1 else 0 end ) as BS,sum(case when isnull(BT,'') !='' then 1 else 0 end ) as BT,sum(case when isnull(BU,'') !='' then 1 else 0 end ) as BU,sum(case when isnull(BV,'') !='' then 1 else 0 end ) as BV,sum(case when isnull(BW,'') !='' then 1 else 0 end ) as BW," +
                "sum(case when isnull(BX,'') !='' then 1 else 0 end ) as BX,sum(case when isnull(BYY,'') !='' then 1 else 0 end ) as BYY,sum(case when isnull(BZ,'') !='' then 1 else 0 end ) as BZ,sum(case when isnull(CA,'') !='' then 1 else 0 end ) as CA,sum(case when isnull(CB,'') !='' then 1 else 0 end ) as CB,sum(case when isnull(CC,'') !='' then 1 else 0 end ) as CC,sum(case when isnull(CD,'') !='' then 1 else 0 end ) as CD,sum(case when isnull(CE,'') !='' then 1 else 0 end ) as CE,sum(case when isnull(CF,'') !='' then 1 else 0 end ) as CF,sum(case when isnull(CG,'') !='' then 1 else 0 end ) as CG,sum(case when isnull(CH,'') !='' then 1 else 0 end ) as CH,sum(case when isnull(CI,'') !='' then 1 else 0 end ) as CI,sum(case when isnull(CJ,'') !='' then 1 else 0 end ) as CJ,sum(case when isnull(CK,'') !='' then 1 else 0 end ) as CK,sum(case when isnull(CL,'') !='' then 1 else 0 end ) as CL,sum(case when isnull(CM,'') !='' then 1 else 0 end ) as CM,sum(case when isnull(CN,'') !='' then 1 else 0 end ) as CN,sum(case when isnull(CO,'') !='' then 1 else 0 end ) as CO,sum(case when isnull(CP,'') !='' then 1 else 0 end ) as CP,sum(case when isnull(CQ,'') !='' then 1 else 0 end ) as CQ,sum(case when isnull(CR,'') !='' then 1 else 0 end ) as CR,sum(case when isnull(CS,'') !='' then 1 else 0 end ) as CS,sum(case when isnull(CT,'') !='' then 1 else 0 end ) as CT,sum(case when isnull(CU,'') !='' then 1 else 0 end ) as CU,sum(case when isnull(CV,'') !='' then 1 else 0 end ) as CV from baitaoquanxian" +
                " where 公司=? and 日期 >= convert(date,?) and 日期 <= convert(date,?)";
        base = new FenquanDao();
        List<Workbench> list = base.query(Workbench.class, sql, company, start_date,stop_date);
        return list;
    }

    public List<Workbench> getRenYuanChart(String company,String name,String start_date, String stop_date) {
        String sql = "select sum(case when isnull(A,'') !='' then 1 else 0 end ) as A,sum(case when isnull(B,'') !='' then 1 else 0 end ) as B,sum(case when isnull(C,'') !='' then 1 else 0 end ) as C,sum(case when isnull(D,'') !='' then 1 else 0 end ) as D,sum(case when isnull(E,'') !='' then 1 else 0 end ) as E,sum(case when isnull(F,'') !='' then 1 else 0 end ) as F,sum(case when isnull(G,'') !='' then 1 else 0 end ) as G,sum(case when isnull(H,'') !='' then 1 else 0 end ) as H,sum(case when isnull(I,'') !='' then 1 else 0 end ) as I,sum(case when isnull(J,'') !='' then 1 else 0 end ) as J,sum(case when isnull(K,'') !='' then 1 else 0 end ) as K,sum(case when isnull(L,'') !='' then 1 else 0 end ) as L,sum(case when isnull(M,'') !='' then 1 else 0 end ) as M,sum(case when isnull(N,'') !='' then 1 else 0 end ) as N,sum(case when isnull(O,'') !='' then 1 else 0 end ) as O,sum(case when isnull(P,'') !='' then 1 else 0 end ) as P,sum(case when isnull(Q,'') !='' then 1 else 0 end ) as Q,sum(case when isnull(R,'') !='' then 1 else 0 end ) as R,sum(case when isnull(S,'') !='' then 1 else 0 end ) as S,sum(case when isnull(T,'') !='' then 1 else 0 end ) as T,sum(case when isnull(U,'') !='' then 1 else 0 end ) as U,sum(case when isnull(V,'') !='' then 1 else 0 end ) as V,sum(case when isnull(W,'') !='' then 1 else 0 end ) as W,sum(case when isnull(X,'') !='' then 1 else 0 end ) as X,sum(case when isnull(Y,'') !='' then 1 else 0 end ) as Y,sum(case when isnull(Z,'') !='' then 1 else 0 end ) as Z,sum(case when isnull(AA,'') !='' then 1 else 0 end ) as AA,sum(case when isnull(AB,'') !='' then 1 else 0 end ) as AB,sum(case when isnull(AC,'') !='' then 1 else 0 end ) as AC,sum(case when isnull(AD,'') !='' then 1 else 0 end ) as AD,sum(case when isnull(AE,'') !='' then 1 else 0 end ) as AE,sum(case when isnull(AF,'') !='' then 1 else 0 end ) as AF,sum(case when isnull(AG,'') !='' then 1 else 0 end ) as AG,sum(case when isnull(AH,'') !='' then 1 else 0 end ) as AH,sum(case when isnull(AI,'') !='' then 1 else 0 end ) as AI,sum(case when isnull(AJ,'') !='' then 1 else 0 end ) as AJ,sum(case when isnull(AK,'') !='' then 1 else 0 end ) as AK,sum(case when isnull(AL,'') !='' then 1 else 0 end ) as AL" +
                ",sum(case when isnull(AM,'') !='' then 1 else 0 end ) as AM,sum(case when isnull(AN,'') !='' then 1 else 0 end ) as AN,sum(case when isnull(AO,'') !='' then 1 else 0 end ) as AO,sum(case when isnull(AP,'') !='' then 1 else 0 end ) as AP,sum(case when isnull(AQ,'') !='' then 1 else 0 end ) as AQ,sum(case when isnull(AR,'') !='' then 1 else 0 end ) as AR,sum(case when isnull(ASS,'') !='' then 1 else 0 end ) as ASS,sum(case when isnull(AT,'') !='' then 1 else 0 end ) as AT,sum(case when isnull(AU,'') !='' then 1 else 0 end ) as AU,sum(case when isnull(AV,'') !='' then 1 else 0 end ) as AV,sum(case when isnull(AW,'') !='' then 1 else 0 end ) as AW,sum(case when isnull(AX,'') !='' then 1 else 0 end ) as AX,sum(case when isnull(AY,'') !='' then 1 else 0 end ) as AY,sum(case when isnull(AZ,'') !='' then 1 else 0 end ) as AZ,sum(case when isnull(BA,'') !='' then 1 else 0 end ) as BA,sum(case when isnull(BB,'') !='' then 1 else 0 end ) as BB,sum(case when isnull(BC,'') !='' then 1 else 0 end ) as BC,sum(case when isnull(BD,'') !='' then 1 else 0 end ) as BD,sum(case when isnull(BE,'') !='' then 1 else 0 end ) as BE,sum(case when isnull(BF,'') !='' then 1 else 0 end ) as BF,sum(case when isnull(BG,'') !='' then 1 else 0 end ) as BG,sum(case when isnull(BH,'') !='' then 1 else 0 end ) as BH,sum(case when isnull(BI,'') !='' then 1 else 0 end ) as BI,sum(case when isnull(BJ,'') !='' then 1 else 0 end ) as BJ,sum(case when isnull(BK,'') !='' then 1 else 0 end ) as BK,sum(case when isnull(BL,'') !='' then 1 else 0 end ) as BL,sum(case when isnull(BM,'') !='' then 1 else 0 end ) as BM,sum(case when isnull(BN,'') !='' then 1 else 0 end ) as BN,sum(case when isnull(BO,'') !='' then 1 else 0 end ) as BO,sum(case when isnull(BP,'') !='' then 1 else 0 end ) as BP,sum(case when isnull(BQ,'') !='' then 1 else 0 end ) as BQ,sum(case when isnull(BR,'') !='' then 1 else 0 end ) as BR,sum(case when isnull(BS,'') !='' then 1 else 0 end ) as BS,sum(case when isnull(BT,'') !='' then 1 else 0 end ) as BT,sum(case when isnull(BU,'') !='' then 1 else 0 end ) as BU,sum(case when isnull(BV,'') !='' then 1 else 0 end ) as BV,sum(case when isnull(BW,'') !='' then 1 else 0 end ) as BW," +
                "sum(case when isnull(BX,'') !='' then 1 else 0 end ) as BX,sum(case when isnull(BYY,'') !='' then 1 else 0 end ) as BYY,sum(case when isnull(BZ,'') !='' then 1 else 0 end ) as BZ,sum(case when isnull(CA,'') !='' then 1 else 0 end ) as CA,sum(case when isnull(CB,'') !='' then 1 else 0 end ) as CB,sum(case when isnull(CC,'') !='' then 1 else 0 end ) as CC,sum(case when isnull(CD,'') !='' then 1 else 0 end ) as CD,sum(case when isnull(CE,'') !='' then 1 else 0 end ) as CE,sum(case when isnull(CF,'') !='' then 1 else 0 end ) as CF,sum(case when isnull(CG,'') !='' then 1 else 0 end ) as CG,sum(case when isnull(CH,'') !='' then 1 else 0 end ) as CH,sum(case when isnull(CI,'') !='' then 1 else 0 end ) as CI,sum(case when isnull(CJ,'') !='' then 1 else 0 end ) as CJ,sum(case when isnull(CK,'') !='' then 1 else 0 end ) as CK,sum(case when isnull(CL,'') !='' then 1 else 0 end ) as CL,sum(case when isnull(CM,'') !='' then 1 else 0 end ) as CM,sum(case when isnull(CN,'') !='' then 1 else 0 end ) as CN,sum(case when isnull(CO,'') !='' then 1 else 0 end ) as CO,sum(case when isnull(CP,'') !='' then 1 else 0 end ) as CP,sum(case when isnull(CQ,'') !='' then 1 else 0 end ) as CQ,sum(case when isnull(CR,'') !='' then 1 else 0 end ) as CR,sum(case when isnull(CS,'') !='' then 1 else 0 end ) as CS,sum(case when isnull(CT,'') !='' then 1 else 0 end ) as CT,sum(case when isnull(CU,'') !='' then 1 else 0 end ) as CU,sum(case when isnull(CV,'') !='' then 1 else 0 end ) as CV from baitaoquanxian" +
                " where 公司=? and 日期 >= convert(date,?) and 日期 <= convert(date,?) and 人员 = ?";
        base = new FenquanDao();
        List<Workbench> list = base.query(Workbench.class, sql, company, start_date,stop_date,name);
        return list;
    }

}
